FROM rust:1.53.0
RUN cargo install diesel_cli
RUN rustup default nightly
RUN apt-get update \
    && apt-get install -y ca-certificates tzdata libpq-dev \
    && rm -rf /var/lib/apt/lists/*
RUN USER=root cargo new --bin api
WORKDIR ./api
COPY api/Cargo.toml ./Cargo.toml
RUN cargo build --release
RUN rm src/*.rs
ADD api ./
RUN rm ./target/release/deps/api*
RUN cargo build --release
EXPOSE $PORT
ENV TZ=Etc/UTC \
    APP_USER=appuser

RUN groupadd $APP_USER \
    && useradd -g $APP_USER $APP_USER
RUN chown -R $APP_USER:$APP_USER .
RUN chmod u+x ./start_api.sh
USER $APP_USER
CMD ["sh", "./start_api.sh"]