[package]
name = "sanity-check-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
snapchallange-lib-rs = { path = "../../client_libraries/snapchallange-lib-rs" }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"