version: '3.9'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: toor

  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      PORT: 3001
      SECRET_KEY: ASDB
      DATABASE_URL: postgres://postgres:toor@db/votingsys
      ADMIN_KEY: almafa
    ports:
      - 3001:3001